// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

// biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js";
import type { AppRoutes, LayoutRoutes, ParamMap } from "@/types/routes.js";

// biome-ignore lint/correctness/noUnusedVariables: Auto-generated by Next.js
type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
    | React.ComponentType<{ params: Promise<ParamMap[Route]> } & any>
    | ((
        // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
        props: { params: Promise<ParamMap[Route]> } & any,
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) =>
    | Promise<
        any[] /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */
      >
    | any[] /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */;
  // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
  generateMetadata?: (
    // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) =>
    | Promise<any /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */>
    | any /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */;
  // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
  generateViewport?: (
    // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) =>
    | Promise<any /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */>
    | any /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */;
  // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
  metadata?: any;
  // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
  viewport?: any;
};

// biome-ignore lint/correctness/noUnusedVariables: Auto-generated by Next.js
type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>,
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) =>
    | Promise<
        any[] /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */
      >
    | any[] /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */;
  // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
  generateMetadata?: (
    // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) =>
    | Promise<any /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */>
    | any /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */;
  // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
  generateViewport?: (
    // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) =>
    | Promise<any /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */>
    | any /* biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js */;
  // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
  metadata?: any;
  // biome-ignore lint/suspicious/noExplicitAny: Auto-generated by Next.js
  viewport?: any;
};
